### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by LuizF14** [LuizF14/trabalho-grafos#1]
- [ ] Implementar uma lista de adjacência
- [ ] Implementar DFS e BFS
- [ ] Implementar Dijkstra
- [ ] Implementar uma matriz de adjacência
- [ ] Implementar o algoritmo de Prim e Kruskal
- [ ] Implementar o algoritmo de Brélaz
- [ ] Implementar o algoritmo Ford-Fulkerson para Fluxo Máximo
- [ ] Implementar o algoritmo de emparelhamento máximo
- [ ] Fazer o menu para o usuário
Pensando em fazer uma classe pai com os filhos sendo a lista de adjacência e matriz de adjacência.
